### ISSUE TITLE
全局关系图连线无法看清

### ISSUE THREAD

**Issue by lss6378** [ihyw/Lavender#1]
思源版本:0.7.0

Lavender 主题下效果如图：
![图片](https://user-images.githubusercontent.com/15924513/106265391-f06da780-6261-11eb-9380-59f098943529.png)

使用思源自带的主题没有问题：
![图片](https://user-images.githubusercontent.com/15924513/106265516-1eeb8280-6262-11eb-8426-a09bb006daba.png)

**Comment by ihyw** [comment]
感谢反馈！等吃完饭我马上把三个主题都修改一下！

**Comment by ihyw** [comment]
老哥，我已PR，等出现更新后，更新一下即可！

**Comment by lss6378** [comment]
> 
> 
> 老哥，我已PR，等出现更新后，更新一下即可！

老铁给力啊，等更新试用后再过来反馈

**Comment by lss6378** [comment]
试用了一波，恢复正常了，感谢^_^
![图片](https://user-images.githubusercontent.com/15924513/106274495-5280d980-626f-11eb-9685-119a9795ce26.png)

**Comment by ihyw** [comment]
客气啦，有需要改进的地方随时交流！
