### ISSUE TITLE
弹窗关闭能否也增加动画呢

### ISSUE THREAD

**Issue by Achuan-2** [ihyw/Lavender#2]
设置弹窗出现和关闭都有动画感觉会协调点

**Comment by ihyw** [comment]
暂时不行，目前主题编写仅提供了 CSS 样式编辑，我之前做这个动画的时候就准备关闭的时候也做，但是控制弹窗显示是由思源的JS来控制的，它只会在它被调用的时候出现，所以纯CSS无法实现开和关都有动画，如果以后可以加入 JS 的控制就可以改进下！感谢提供意见！。
